---
name: Terraform Generic Plan
run-name: >-
  Terraform Generic Plan of PR ${{ github.event.pull_request.number }} by @${{ github.actor }}

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - converted_to_draft
      - ready_for_review
    branches: [main]
    paths:
      # - terraform/datadog/** # need to fix secrets before onboarding here
      - terraform/cloudflare/**
      - terraform/jfrog/**

permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write

jobs:
  sort-changed-files:
    runs-on: gha-runner-scale-set
    outputs:
      changed-dir: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          dir_names: 'true'
          matrix: true
          path: .
          files: |
              terraform/cloudflare/**
              terraform/jfrog/**
              # terraform/datadog/**

      # TODO: need simple logic to determinte terraform root dir by looking for backend.tf

  tf-plan-generic:
    if: needs.sort-changed-files.outputs.changed-dir != '[]'
    needs: sort-changed-files
    runs-on: gha-runner-scale-set
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        tf_stacks: ${{ fromJson(needs.sort-changed-files.outputs.changed-dir) }}
    env:
      tf_stack: ${{ matrix.tf_stacks }}
    steps:
      - uses: actions/checkout@v4

      - name: Parse Enviroment
        id: parse-env
        env: # GENERIC tf states were stored in shared-services S3 Bucket
          aws_account_name: shared-services
          aws_account_id: "273354621727"
        run: |
          # parse env

          echo "aws_account_name=${{ env.aws_account_name }}" | tee -a $GITHUB_OUTPUT
          echo "aws_account_id=${{ env.aws_account_id }}" | tee -a $GITHUB_OUTPUT

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::${{ steps.parse-env.outputs.aws_account_id }}:role/FutureSecureAI-Admin-GitHub-actions-runner
          aws-region: ap-southeast-2

      - name: terraform plan
        id: terraform-plan
        uses: ./.github/actions/tf-command
        with:
          cloud_account: ${{ steps.parse-env.outputs.aws_account_name }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          tf_layer: overlay
          tf_stack: ${{ env.tf_stack }}
          tf_command: plan
