---
name: Terraform Azure Plan Base
run-name: >-
  Terraform Azure Plan Base of PR ${{ github.event.pull_request.number }} by @${{ github.actor }}

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - converted_to_draft
      - ready_for_review
    branches: [main]
    paths:
      - terraform/azure/base/**

permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write

jobs:
  sort-changed-files:
    runs-on: gha-runner-scale-set
    outputs:
      tf-variables-matrix: ${{ steps.get-tf-changed-dir.outputs.tf-variables }}
      base-infra-matrix: ${{ steps.get-tf-changed-dir.outputs.base-infra }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed TF directories
        id: get-tf-changed-dir
        uses: ./.github/actions/tf-matrix
        with:
          filter: |
            terraform/azure/base/**

  get-all-azure-subscriptions:
    runs-on: gha-runner-scale-set
    if: needs.sort-changed-files.outputs.base-infra-matrix != '[]'
    needs: sort-changed-files
    outputs:
      azure-subscription-name-matrix: ${{ steps.get-all-azure-subscriptions.outputs.azure_subscription_names }}
    env:
      reference: terraform/azure/base/_env/tf-variables/*.tfvars
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get all Azure Subscriptions
        id: get-all-azure-subscriptions
        run: |
          # step: get-all-azure-subscriptions

          array=($(ls ${{ env.reference }} | xargs -n 1 basename -s .tfvars ))
          json="$(printf '%s\n' "${array[@]}" | jq -R . |  jq -s -c . )"
          echo "azure_subscription_names=$json" | tee -a $GITHUB_OUTPUT

  get-all-base-stacks:
    runs-on: gha-runner-scale-set
    if: needs.sort-changed-files.outputs.tf-variables-matrix != '[]'
    needs: sort-changed-files
    outputs:
      tf-all-base-stacks-matrix: ${{ steps.get-all-base-stacks.outputs.tf_all_base_stacks }}
    env:
      reference: terraform/azure/base
      exclude: terraform-state
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get all base stacks
        id: get-all-base-stacks
        run: |
          # step: get-all-base-stacks

          echo "excluding: ${{ env.reference }}/${{ env.exclude }}"
          array=($(
            find ${{ env.reference }} \
              -type d -name ${{ env.exclude }} -prune -o \
              -type f -name backend.tf -print \
               | xargs -n1 dirname \
               | sort -u
          ))
          json="$(printf '%s\n' "${array[@]}" | jq -R . | jq -s -c . )"
          echo "tf_all_base_stacks=$json" | tee -a $GITHUB_OUTPUT

  tf-plan-base-all-accounts:
    if: >
      needs.sort-changed-files.outputs.base-infra-matrix != '[]' &&
      needs.sort-changed-files.outputs.tf-variables-matrix == '[]'
    needs:
      - sort-changed-files
      - get-all-azure-subscriptions
    runs-on: gha-runner-scale-set
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        tf_stacks: ${{ fromJson(needs.sort-changed-files.outputs.base-infra-matrix) }}
        azure_subscription_names: ${{ fromJson(needs.get-all-azure-subscriptions.outputs.azure-subscription-name-matrix) }}
    env:
      tf_stack: ${{ matrix.tf_stacks }}
      azure_subscription_name: ${{ matrix.azure_subscription_names }}
    steps:
      - uses: actions/checkout@v4

      - name: Get Environment
        id: get-env
        uses: ./.github/actions/get-env-azure
        with:
          azure_subscription: ${{ env.azure_subscription_name }}

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ steps.get-env.outputs.azure_client_id }}
          tenant-id: ${{ steps.get-env.outputs.azure_tenant_id }}
          subscription-id: ${{ steps.get-env.outputs.azure_subscription_id }}

      - name: terraform plan
        id: terraform-plan
        uses: ./.github/actions/tf-command
        env:
          ARM_USE_OIDC: true
          ARM_CLIENT_ID: ${{ steps.get-env.outputs.azure_client_id }}
          ARM_TENANT_ID: ${{ steps.get-env.outputs.azure_tenant_id }}
          ARM_SUBSCRIPTION_ID: ${{ steps.get-env.outputs.azure_subscription_id }}
        with:
          cloud_account: ${{ env.azure_subscription_name }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          tf_layer: base
          tf_stack: ${{ env.tf_stack }}
          tf_command: plan

  tf-plan-base-all-stacks:
    if: >
      needs.sort-changed-files.outputs.tf-variables-matrix != '[]' &&
      needs.sort-changed-files.outputs.base-infra-matrix == '[]'
    needs:
      - sort-changed-files
      - get-all-base-stacks
    runs-on: gha-runner-scale-set
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        tf_all_base_stacks: ${{ fromJson(needs.get-all-base-stacks.outputs.tf-all-base-stacks-matrix) }}
        tf_variables: ${{ fromJson(needs.sort-changed-files.outputs.tf-variables-matrix) }}
    env:
      tf_stack: ${{ matrix.tf_all_base_stacks }}
      tf_variables: ${{ matrix.tf_variables }}
    steps:
      - uses: actions/checkout@v4

      - name: Parse Enviroment
        id: parse-env
        run: |
          azure_subscription_name=$( basename $(echo ${{ env.tf_variables }} | cut -d'/' -f6) .tfvars )
          echo "azure_subscription_name=$azure_subscription_name" | tee -a $GITHUB_OUTPUT

      - name: Get Environment
        id: get-env
        uses: ./.github/actions/get-env-azure
        with:
          azure_subscription: ${{ steps.parse-env.outputs.azure_subscription_name }}

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ steps.get-env.outputs.azure_client_id }}
          tenant-id: ${{ steps.get-env.outputs.azure_tenant_id }}
          subscription-id: ${{ steps.get-env.outputs.azure_subscription_id }}

      - name: terraform plan
        id: terraform-plan
        uses: ./.github/actions/tf-command
        env:
          ARM_USE_OIDC: true
          ARM_CLIENT_ID: ${{ steps.get-env.outputs.azure_client_id }}
          ARM_TENANT_ID: ${{ steps.get-env.outputs.azure_tenant_id }}
          ARM_SUBSCRIPTION_ID: ${{ steps.get-env.outputs.azure_subscription_id }}
        with:
          cloud_account: ${{ steps.parse-env.outputs.azure_subscription_name }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          tf_layer: base
          tf_stack: ${{ env.tf_stack }}
          tf_command: plan

  tf-plan-base-everything:
    if: >
      needs.sort-changed-files.outputs.tf-variables-matrix != '[]' &&
      needs.sort-changed-files.outputs.base-infra-matrix != '[]'
    needs:
      - sort-changed-files
      - get-all-base-stacks
      - get-all-azure-subscriptions
    runs-on: gha-runner-scale-set
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        tf_all_base_stacks: ${{ fromJson(needs.get-all-base-stacks.outputs.tf-all-base-stacks-matrix) }}
        azure_subscription_names: ${{ fromJson(needs.get-all-azure-subscriptions.outputs.azure-subscription-name-matrix) }}
    env:
      tf_stack: ${{ matrix.tf_all_base_stacks }}
      azure_subscription_name: ${{ matrix.azure_subscription_names }}
    steps:
      - uses: actions/checkout@v4

      - name: Get Environment
        id: get-env
        uses: ./.github/actions/get-env-azure
        with:
          azure_subscription: ${{ env.azure_subscription_name }}

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ steps.get-env.outputs.azure_client_id }}
          tenant-id: ${{ steps.get-env.outputs.azure_tenant_id }}
          subscription-id: ${{ steps.get-env.outputs.azure_subscription_id }}

      - name: terraform plan
        id: terraform-plan
        uses: ./.github/actions/tf-command
        env:
          ARM_USE_OIDC: true
          ARM_CLIENT_ID: ${{ steps.get-env.outputs.azure_client_id }}
          ARM_TENANT_ID: ${{ steps.get-env.outputs.azure_tenant_id }}
          ARM_SUBSCRIPTION_ID: ${{ steps.get-env.outputs.azure_subscription_id }}
        with:
          cloud_account: ${{ env.azure_subscription_name }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          tf_layer: base
          tf_stack: ${{ env.tf_stack }}
          tf_command: plan
