name: Terraform Generic Manual
run-name: >-
  ${{ inputs.saas_provider }}: terraform ${{ inputs.tf_command }} @ ${{ inputs.tf_stack }}

on:
  workflow_dispatch:
   inputs:
      saas_provider:
        description: >-
          saas_provider (Required):
          saas provider name on which
          terraform state file is
          located
        type: choice
        required: true
        default: cloudflare
        options:
          - cloudflare
          - datadog
          - jfrog

      tf_stack:
        description: >-
          tf_stack (Required):
          Targeted Directory which tf-command will be executed.
          The path starts after saas_provider.
        type: string
        required: true

      tf_command:
        description: >-
          tf_command (Required):
          terraform command to execute
        type: choice
        required: true
        default: plan
        options:
          - plan
          - apply

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: "${{ inputs.aws_account_name }}-${{ inputs.tf_layer }}-terraform"
    runs-on: gha-runner-scale-set
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Parse Enviroment
        id: parse-env
        env: # GENERIC tf states were stored in shared-services S3 Bucket
          aws_account_name: shared-services
          aws_account_id: "273354621727"
        run: |
          # parse env

          echo "aws_account_name=${{ env.aws_account_name }}" | tee -a $GITHUB_OUTPUT
          echo "aws_account_id=${{ env.aws_account_id }}" | tee -a $GITHUB_OUTPUT

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::${{ steps.parse-env.outputs.aws_account_id }}:role/FutureSecureAI-Admin-GitHub-actions-runner
          aws-region: ap-southeast-2

      - name: Terraform Generic ${{ inputs.tf_command }}
        uses: ./.github/actions/tf-command
        with:
          cloud_account: ${{ steps.parse-env.outputs.aws_account_name }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          tf_layer: overlay
          tf_stack: terraform/${{ inputs.saas_provider }}/${{ inputs.tf_stack }}
          tf_command: ${{ inputs.tf_command }}
